DROP INDEX IF EXISTS im_friend_requests_expiry_idx;
DROP INDEX IF EXISTS im_friend_requests_pending_idx;
ALTER TABLE im_friend_requests DROP COLUMN IF EXISTS resolved_at;
ALTER TABLE im_friend_requests DROP COLUMN IF EXISTS updated_at;
ALTER TABLE im_friend_requests DROP COLUMN IF EXISTS expires_at;
ALTER TABLE im_friend_requests DROP COLUMN IF EXISTS source;
ALTER TABLE im_friend_requests DROP COLUMN IF EXISTS source_id;
ALTER TABLE im_friendships DROP COLUMN IF EXISTS updated_at;
ALTER TABLE im_friendships DROP COLUMN IF EXISTS tags;
ALTER TABLE im_friendships DROP COLUMN IF EXISTS remark;
